### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by girlwithglasses** [yanick/Dancer2-Plugin-Cache-CHI#6]
cpan[3]> install Dancer2::Plugin::Cache::CHI
	Running install for module 'Dancer2::Plugin::Cache::CHI'
	  YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz
	  Has already been unwrapped into directory /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT
	Configuring Y/YA/YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz with Build.PL
	Created MYMETA.yml and MYMETA.json
	Creating new 'Build' script for 'Dancer2-Plugin-Cache-CHI' version '1.6.0'
	  YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz
	  /Users/gwg/perl5/perlbrew/perls/perl-5.16.3/bin/perl Build.PL -- OK
	Running Build for Y/YA/YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz
	Building Dancer2-Plugin-Cache-CHI
	  YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz
	  ./Build -- OK
	Running Build test
	t/000-report-versions-tiny.t .. # 
	# 
	# Generated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.10
	# perl: 5.016003 (wanted v5.10.0) on darwin from /Users/gwg/perl5/perlbrew/perls/perl-5.16.3/bin/perl
	# 
	# CHI                                           => 0.60       (want any version)
	# Carp                                          => 1.36       (want any version)
	# Dancer2                                       => 0.160003   (want 0.140001)
	# Dancer2::Plugin                               => 0.160003   (want any version)
	# HTTP::Request::Common                         => 6.04       (want any version)
	# Module::Build                                 => 0.4214     (want 0.3601) 
	# Moo                                           => 2.000001   (want 1.000007)
	# Plack::Test                                   => <undef>    (want any version)
	# Test::More                                    => 1.001014   (want 0.88)   
	# lib                                           => 0.63       (want any version)
	# strict                                        => 1.07       (want any version)
	# warnings                                      => 1.13       (want any version)
	# 
	# Thanks for using my code.  I hope it works for you.
	# If not, please try and include this output in the bug report.
	# That will help me reproduce the issue and solve your problem.
	# 
	t/000-report-versions-tiny.t .. ok   
	t/basic.t ..................... 1/25 
	#   Failed test '/cached (cached!)'
	#   at t/basic.t line 26.
	#          got: 'Internal Server Error
	# 
	# Hook error: response is a read-only accessor at (eval 246)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
	#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Role/Hookable.pm line 114.
	# '
	#     expected: '2'
	[TestApp:72371] error @2015-09-16 12:20:16> Route exception: isa check for "content" failed: HASH(0x7f99fc135eb0) is not a string! at (eval 99)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 31.
		eval {...} called at (eval 99)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 29
		Dancer2::Core::Response::content(Dancer2::Core::Response=HASH(0x7f99fc135ec8), HASH(0x7f99fc135eb0)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Response.pm line 76
		Dancer2::Core::Response::__ANON__(CODE(0x7f99f94d38a8), Dancer2::Core::Response=HASH(0x7f99fc135ec8), HASH(0x7f99fc135eb0)) called at (eval 101)[/Users/gwg/perl5/lib/perl5/Class/Method/Modifiers.pm:93] line 1
		Dancer2::Core::Response::__ANON__(Dancer2::Core::Response=HASH(0x7f99fc135ec8), HASH(0x7f99fc135eb0)) called at (eval 103)[/Users/gwg/perl5/lib/perl5/Class/Method/Modifiers.pm:152] line 2
		Dancer2::Core::Response::content(Dancer2::Core::Response=HASH(0x7f99fc135ec8), HASH(0x7f99fc135eb0)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1386
		Dancer2::Core::App::_add_content_to_response(Dancer2::Core::App=HASH(0x7f99f95a7248), Dancer2::Core::Response=HASH(0x7f99fc135ec8), HASH(0x7f99fc135eb0)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Route.pm line 144
		Dancer2::Core::Route::execute(Dancer2::Core::Route=HASH(0x7f99f96fb530), Dancer2::Core::App=HASH(0x7f99f95a7248)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1362
		eval {...} called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1363
		Dancer2::Core::App::_dispatch_route(Dancer2::Core::App=HASH(0x7f99f95a7248), Dancer2::Core::Route=HASH(0x7f99f96fb530)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1251
		Dancer2::Core::App::__ANON__ called at /Users/gwg/perl5/lib/perl5/Return/MultiLevel.pm line 61
		Return::MultiLevel::__ANON__(ARRAY(0x7f99fc081768), CODE(0x7f99fc0fa900), CODE(0x7f99fc136360)) called at /Users/gwg/perl5/lib/perl5/Return/MultiLevel.pm line 97
		Return::MultiLevel::with_return(CODE(0x7f99fc0fa900)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1252
		Dancer2::Core::App::dispatch(Dancer2::Core::App=HASH(0x7f99f95a7248), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1169
		eval {...} called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1171
		Dancer2::Core::App::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/RemoveRedundantBody.pm line 14
		Plack::Middleware::RemoveRedundantBody::call(Plack::Middleware::RemoveRedundantBody=HASH(0x7f99f977e608), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/FixMissingBodyInRedirect.pm line 50
		Plack::Middleware::FixMissingBodyInRedirect::call(Plack::Middleware::FixMissingBodyInRedirect=HASH(0x7f99f977e7a0), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/ContentLength.pm line 10
		Plack::Middleware::ContentLength::call(Plack::Middleware::ContentLength=HASH(0x7f99f977e938), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/Conditional.pm line 16
		Plack::Middleware::Conditional::call(Plack::Middleware::Conditional=HASH(0x7f99f977f028), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/Head.pm line 9
		Plack::Middleware::Head::call(Plack::Middleware::Head=HASH(0x7f99f977f118), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Dispatcher.pm line 36
		Dancer2::Core::Dispatcher::dispatch(Dancer2::Core::Dispatcher=HASH(0x7f99f97b0eb0), HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Runner.pm line 212
		Dancer2::Core::Runner::__ANON__(HASH(0x7f99f97d9948)) called at /Users/gwg/perl5/lib/perl5/Plack/Test/MockHTTP.pm line 24
		Plack::Test::MockHTTP::try {...} () called at /Users/gwg/perl5/lib/perl5/Try/Tiny.pm line 79
		eval {...} called at /Users/gwg/perl5/lib/perl5/Try/Tiny.pm line 72
		Try::Tiny::try(CODE(0x7f99fc150060), Try::Tiny::Catch=REF(0x7f99f97e1990)) called at /Users/gwg/perl5/lib/perl5/Plack/Test/MockHTTP.pm line 27
		Plack::Test::MockHTTP::request(Plack::Test::MockHTTP=HASH(0x7f99f978b0e0), HTTP::Request=HASH(0x7f99fc136108)) called at /Users/gwg/perl5/lib/perl5/Plack/Test.pm line 38
		Plack::Test::__ANON__(HTTP::Request=HASH(0x7f99fc136108)) called at t/basic.t line 29
		main::__ANON__(CODE(0x7f99f978b110)) called at /Users/gwg/perl5/lib/perl5/Plack/Test.pm line 38
		Plack::Test::test_psgi("app", CODE(0x7f99f94ec4a8), "client", CODE(0x7f99f97884a0)) called at t/basic.t line 63 in /Users/gwg/perl5/lib/perl5/Return/MultiLevel.pm l. 61

	#   Failed test '/clear'
	#   at t/basic.t line 29.
	#          got: '500'
	#     expected: '200'
	[TestApp:72371] error @2015-09-16 12:20:16> Route exception: isa check for "content" failed: HASH(0x7f99f92cc808) is not a string! at (eval 99)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 31.
		eval {...} called at (eval 99)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 29
		Dancer2::Core::Response::content(Dancer2::Core::Response=HASH(0x7f99fc191de8), HASH(0x7f99f92cc808)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Response.pm line 76
		Dancer2::Core::Response::__ANON__(CODE(0x7f99f94d38a8), Dancer2::Core::Response=HASH(0x7f99fc191de8), HASH(0x7f99f92cc808)) called at (eval 101)[/Users/gwg/perl5/lib/perl5/Class/Method/Modifiers.pm:93] line 1
		Dancer2::Core::Response::__ANON__(Dancer2::Core::Response=HASH(0x7f99fc191de8), HASH(0x7f99f92cc808)) called at (eval 103)[/Users/gwg/perl5/lib/perl5/Class/Method/Modifiers.pm:152] line 2
		Dancer2::Core::Response::content(Dancer2::Core::Response=HASH(0x7f99fc191de8), HASH(0x7f99f92cc808)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1386
		Dancer2::Core::App::_add_content_to_response(Dancer2::Core::App=HASH(0x7f99f95a7248), Dancer2::Core::Response=HASH(0x7f99fc191de8), HASH(0x7f99f92cc808)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Route.pm line 144
		Dancer2::Core::Route::execute(Dancer2::Core::Route=HASH(0x7f99f96fb530), Dancer2::Core::App=HASH(0x7f99f95a7248)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1362
		eval {...} called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1363
		Dancer2::Core::App::_dispatch_route(Dancer2::Core::App=HASH(0x7f99f95a7248), Dancer2::Core::Route=HASH(0x7f99f96fb530)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1251
		Dancer2::Core::App::__ANON__ called at /Users/gwg/perl5/lib/perl5/Return/MultiLevel.pm line 61
		Return::MultiLevel::__ANON__(ARRAY(0x7f99f91c93b0), CODE(0x7f99fc150648), CODE(0x7f99fc1920e8)) called at /Users/gwg/perl5/lib/perl5/Return/MultiLevel.pm line 97
		Return::MultiLevel::with_return(CODE(0x7f99fc150648)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1252
		Dancer2::Core::App::dispatch(Dancer2::Core::App=HASH(0x7f99f95a7248), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1169
		eval {...} called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 1171
		Dancer2::Core::App::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/RemoveRedundantBody.pm line 14
		Plack::Middleware::RemoveRedundantBody::call(Plack::Middleware::RemoveRedundantBody=HASH(0x7f99f977e608), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/FixMissingBodyInRedirect.pm line 50
		Plack::Middleware::FixMissingBodyInRedirect::call(Plack::Middleware::FixMissingBodyInRedirect=HASH(0x7f99f977e7a0), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/ContentLength.pm line 10
		Plack::Middleware::ContentLength::call(Plack::Middleware::ContentLength=HASH(0x7f99f977e938), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/Conditional.pm line 16
		Plack::Middleware::Conditional::call(Plack::Middleware::Conditional=HASH(0x7f99f977f028), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Middleware/Head.pm line 9
		Plack::Middleware::Head::call(Plack::Middleware::Head=HASH(0x7f99f977f118), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Component.pm line 50
		Plack::Component::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Dispatcher.pm line 36
		Dancer2::Core::Dispatcher::dispatch(Dancer2::Core::Dispatcher=HASH(0x7f99f97b0eb0), HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Runner.pm line 212
		Dancer2::Core::Runner::__ANON__(HASH(0x7f99f9316478)) called at /Users/gwg/perl5/lib/perl5/Plack/Test/MockHTTP.pm line 24
		Plack::Test::MockHTTP::try {...} () called at /Users/gwg/perl5/lib/perl5/Try/Tiny.pm line 79
		eval {...} called at /Users/gwg/perl5/lib/perl5/Try/Tiny.pm line 72
		Try::Tiny::try(CODE(0x7f99f93164a8), Try::Tiny::Catch=REF(0x7f99fc1502a0)) called at /Users/gwg/perl5/lib/perl5/Plack/Test/MockHTTP.pm line 27
		Plack::Test::MockHTTP::request(Plack::Test::MockHTTP=HASH(0x7f99f978b0e0), HTTP::Request=HASH(0x7f99fc135fa0)) called at /Users/gwg/perl5/lib/perl5/Plack/Test.pm line 38
		Plack::Test::__ANON__(HTTP::Request=HASH(0x7f99fc135fa0)) called at t/basic.t line 42
		main::__ANON__(CODE(0x7f99f978b110)) called at /Users/gwg/perl5/lib/perl5/Plack/Test.pm line 38
		Plack::Test::test_psgi("app", CODE(0x7f99f94ec4a8), "client", CODE(0x7f99f97884a0)) called at t/basic.t line 63 in /Users/gwg/perl5/lib/perl5/Return/MultiLevel.pm l. 61

	#   Failed test '/clear cache'
	#   at t/basic.t line 42.
	#          got: '500'
	#     expected: '200'

	#   Failed test at t/basic.t line 46.
	#          got: 'Internal Server Error
	# 
	# Hook error: response is a read-only accessor at (eval 246)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
	#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Role/Hookable.pm line 114.
	# '
	#     expected: '1'
	Argument "Internal Server Error\n\nHook error: response is a read-..." isn't numeric in numeric eq (==) at t/basic.t line 54.
	t/basic.t ..................... 22/25 
	#   Failed test at t/basic.t line 62.
	#          got: undef
	#     expected: '1'
	# Looks like you failed 5 tests of 25.
	t/basic.t ..................... Dubious, test returned 5 (wstat 1280, 0x500)
	Failed 5/25 subtests 
	t/honor-no-cache.t ............ 1/5 Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	[TestApp:72373] error @2015-09-16 12:20:19> Exception caught in 'core.app.before_request' filter: Hook error: response is a read-only accessor at (eval 257)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
	 at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 953. in /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm l. 526

	#   Failed test 'cached (1)'
	#   at t/honor-no-cache.t line 41.
	#          got: 'Internal Server Error
	# 
	# Exception caught in 'core.app.before_request' filter: Hook error: response is a read-only accessor at (eval 257)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
	#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 953.
	#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Role/Hookable.pm line 114.
	# '
	#     expected: '1'
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	[TestApp:72373] error @2015-09-16 12:20:19> Exception caught in 'core.app.before_request' filter: Hook error: response is a read-only accessor at (eval 257)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
	 at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 953. in /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm l. 526
	
		#   Failed test 'cached again (2)'
		#   at t/honor-no-cache.t line 46.
		#          got: 'Internal Server Error
		# 
		# Exception caught in 'core.app.before_request' filter: Hook error: response is a read-only accessor at (eval 257)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
		#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 953.
		#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Role/Hookable.pm line 114.
		# '
		#     expected: '2'
		# Looks like you failed 1 test of 2.

	#   Failed test 'Cache-Control'
	#   at t/honor-no-cache.t line 47.
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	Use of uninitialized value in string eq at /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib/Dancer2/Plugin/Cache/CHI.pm line 105.
	[TestApp:72373] error @2015-09-16 12:20:19> Exception caught in 'core.app.before_request' filter: Hook error: response is a read-only accessor at (eval 257)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
	 at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 953. in /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm l. 526
	
		#   Failed test 'cached again (3)'
		#   at t/honor-no-cache.t line 46.
		#          got: 'Internal Server Error
		# 
		# Exception caught in 'core.app.before_request' filter: Hook error: response is a read-only accessor at (eval 257)[/Users/gwg/perl5/lib/perl5/Sub/Quote.pm:3] line 18.
		#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/App.pm line 953.
		#  at /Users/gwg/perl5/lib/perl5/Dancer2/Core/Role/Hookable.pm line 114.
		# '
		#     expected: '3'
		# Looks like you failed 1 test of 2.

	#   Failed test 'Pragma'
	#   at t/honor-no-cache.t line 47.
	# Looks like you failed 3 tests of 5.
	t/honor-no-cache.t ............ Dubious, test returned 3 (wstat 768, 0x300)
	Failed 3/5 subtests 
	t/hooks.t ..................... ok   
	t/init-check-page-cache.t ..... ok   
	t/key-gen.t ................... ok   
	t/namespaces.t ................ skipped: File::Temp and CHI::Driver::FastMmap required for these tests (Can't locate Cache/FastMmap.pm in @INC (@INC contains: /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/arch /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/lib /Users/gwg/.cpan/build/Dancer2-Plugin-Cache-CHI-1.6.0-tbxRJT/blib/arch /Users/gwg/perl5/lib/perl5/darwin-2level /Users/gwg/perl5/lib/perl5/darwin-2level /Users/gwg/perl5/lib/perl5 /Users/gwg/perl5/lib/perl5/darwin-2level /Users/gwg/perl5/lib/perl5 /Users/gwg/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/darwin-2level /Users/gwg/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3 /Users/gwg/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/darwin-2level /Users/gwg/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3 .) at /Users/gwg/perl5/lib/perl5/CHI/Driver/FastMmap.pm line 4.

	Test Summary Report
	-------------------
	t/basic.t                   (Wstat: 1280 Tests: 25 Failed: 5)
	  Failed tests:  8, 10, 18, 21, 25
	  Non-zero exit status: 5
	t/honor-no-cache.t          (Wstat: 768 Tests: 5 Failed: 3)
	  Failed tests:  3-5
	  Non-zero exit status: 3
	Files=7, Tests=42,  6 wallclock secs ( 0.03 usr  0.01 sys +  3.54 cusr  0.23 csys =  3.81 CPU)
	Result: FAIL
	Failed 2/7 test programs. 8/42 subtests failed.
	  YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz
	  ./Build test -- NOT OK
	//hint// to see the cpan-testers results for installing this module, try:
	  reports YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz
	Failed during this command:
	 YANICK/Dancer2-Plugin-Cache-CHI-1.6.0.tar.gz : make_test NO

**Comment by girlwithglasses** [comment]
There are two issues here: firstly, the `response` object cannot be replaced directly; it has to be modified instead, and secondly, the cache_clear method in TestApp.pm, which returns an empty hashref, which Dancer2 sets as the response's content, throwing an error as the content should be a string. I will submit my patched version that passes the test suite.

**Comment by yanick** [comment]
Thanks a bunch for the patch! Much appreciated. :-)
