### ISSUE TITLE
Dancer2::Plugin2 compatibility

### ISSUE THREAD

**Issue by girlwithglasses** [yanick/Dancer2-Plugin-Cache-CHI#9]
Dancer2 has updated its plugin system; would you be able to update this plugin to be compatible with the new system?

More information:
https://github.com/PerlDancer/Dancer2/issues/1078

**Comment by yanick** [comment]
I'll see what I can do. ^.^

**Comment by yanick** [comment]
Done!

**Comment by girlwithglasses** [comment]
Thank you!
